// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoScrollController from "./auto_scroll_controller"
application.register("auto-scroll", AutoScrollController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import ColorAnswersController from "./color_answers_controller"
application.register("color-answers", ColorAnswersController)

import GamesBlockController from "./games_block_controller"
application.register("games-block", GamesBlockController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PopUpController from "./pop_up_controller"
application.register("pop-up", PopUpController)
